# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTEAJaw92b8aU1k7uTnRepdxT0HsmK7h
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from mpl_toolkits.mplot3d import Axes3D

file = 'Shark.csv'
df = pd.read_csv(file)

X = df[['Valuation Offered', 'Number of sharks in deal']].values.reshape(-1,2)
Y = df['Total Deal Amount']

x = X[:, 0]
y = X[:, 1]
z = Y

from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.stats.diagnostic import het_white
import pandas as pd
import statsmodels.api as sm

x = sm.add_constant(x)
y = sm.add_constant(y)

from statsmodels.stats.diagnostic import het_breuschpagan

model1 = sm.OLS(z, x).fit()
model2 = sm.OLS(z, y).fit()
print("White Test for checking hetersoskedaticity:")
w_test1 = het_white(model1.resid, model1.model.exog)
w_test2 = het_white(model2.resid, model2.model.exog)
label = ['LM Statistic', 'LM-Test p-value', 'F-Statistic', 'F-Test p-value']
print(dict(zip(label, w_test1)))
print(dict(zip(label, w_test2)))

